remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
name:  me big haxor man lol
title: Lafora Disease Awareness
markdown: GFM
description: Lafora Disease
github:
  is_project_page: false
